language: node_js
node_js:
  - "4"
compiler: clang-3.6
cache:
  directories:
    - node_modules
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
